{
 "title": "Ocserv VPN Sessions",
 "tags": [
  "ocserv",
  "vpn"
 ],
 "refresh": "30s",
 "panels": [
  {
   "title": "Active Session Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ocserv_user_bytes_rx" },
    { "expr": "ocserv_user_bytes_tx" },
    { "expr": "ocserv_user_connected_seconds" }
   ]
  },
  {
   "title": "Per Session Traffic (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ocserv_user_bytes_rx + ocserv_user_bytes_tx) and on(username, session_id, ip, vpn_ip, device) topk(10, (ocserv_user_bytes_rx @ end() + ocserv_user_bytes_tx @ end()) and on(username, session_id, ip, vpn_ip, device) ocserv_user_connected_seconds @ end())",
     "legendFormat": "{{username}} #{{session_id}}"
    }
   ]
  },
  {
   "title": "Session Traffic Ranking (Top 10)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, (ocserv_user_bytes_rx + ocserv_user_bytes_tx) and on(username, session_id, ip, vpn_ip, device) ocserv_user_connected_seconds @ end())",
     "legendFormat": "{{username}} #{{session_id}}"
    }
   ]
  },
  {
   "title": "Connection Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ocserv_user_connected_seconds and on(username, session_id, ip, vpn_ip, device) ocserv_user_connected_seconds @ end()",
     "legendFormat": "{{username}} #{{session_id}}"
    }
   ]
  },
  {
   "title": "Per Session Rate (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(ocserv_user_bytes_rx_rate_bytes_per_second + ocserv_user_bytes_tx_rate_bytes_per_second) and on(username, session_id, ip, vpn_ip, device) topk(10, (ocserv_user_bytes_rx_rate_bytes_per_second @ end() + ocserv_user_bytes_tx_rate_bytes_per_second @ end()) and on(username, session_id, ip, vpn_ip, device) ocserv_user_connected_seconds @ end())",
     "legendFormat": "{{username}} #{{session_id}}"
    }
   ]
  }
 ]
}